### ISSUE TITLE
Slot casing

### ISSUE THREAD

**Issue by allanpope** [jahilldev/component-elements#16]
Hey,

If I add an attribute to my web component eg: `foo-bar="123"`, it will be available in the components props as `fooBar`.

If I pass through a slot eg: `<p slot="hello-world">Hello</p>`, it will be available in the components props as `hello-world`. Is it possible to get slot attributes coming through in camelcase?

**Comment by jahilldev** [comment]
Hi @allanpope! 

Thanks for reaching out.

If I understand correctly, you're proposing we normalise the slot keys from a casing (snake, kebab, pascal, etc), into camelCase?

I can't see any immediate issues with this, other than making sure the logic that does this can handle the potential variations in casing I mention above. We probably can't assume someone will use one or another. 

When I get a minute I'll take a look into doing this, otherwise, feel free to have a go, all contributions welcome 👍 

I'll post back here when I have something to review.

Thanks

**Comment by jahilldev** [comment]
@allanpope While we look into doing this, you could destructure using computed properties. Not the cleanest solution, I know:

```javascript
const { ['hello-world']: helloWorld } = props;
```

I'm going to have a bash at this sometime this week, will let you know how I get on.

I'll provide support for the major casing types, as others might have different requirements, e.g Pascal, snake_case, and kebab-case.

**Comment by jahilldev** [comment]
Hi @allanpope,

Apologies for the delay, I've just opened a PR that does the above, handling common casing conventions including "Sentence Case" (just for fun).

https://github.com/jahilldev/component-elements/pull/17

Let me know what you think.

I'll merge and deploy soon.

Thanks 👍

**Comment by allanpope** [comment]
@jahilldev awesome 🎉, appreciate it

**Comment by jahilldev** [comment]
@allanpope I've just merged and published `preactement@v1.8.0` and `reactement@1.1.0`.

Let me know how you get on, feedback either way!

Thanks 👍

**Comment by jahilldev** [comment]
@allanpope I'm going to close this issue for now, let me know if you have any issues and we can revisit.

Thanks again for contributing! 👍

**Comment by allanpope** [comment]
Worked great, cheers
