### ISSUE TITLE
Support Node 18.x

### ISSUE THREAD

**Issue by Half-Shot** [jahilldev/component-elements#24]
I noticed that the package.json requires Node 16, but 18 has been LTS for a while. This presumably needs testing & updating.

**Comment by jahilldev** [comment]
Hi @Half-Shot,

Thanks for helping out, yeh so the `engines` property is currently set to Node >=10, due to us building ES2016 for the distributable. This doesn't mean we don't support version higher than this, however. Both packages should work just fine on the latest LTS.

Our CI process is still using Node 16 LTS, however, so I'm going to update that later today.

Appreciate the help 👍

**Comment by jahilldev** [comment]
I've just realised you're referring to the **root** `package.json`, which shouldn't have this property, so I've removed 👍

**Comment by jahilldev** [comment]
Merged, thanks again, @Half-Shot

**Comment by Half-Shot** [comment]
Thanks!
